### ISSUE TITLE
Mods Not Loading.

### ISSUE THREAD

**Issue by FridayNightFunkinGame** [bobydob/bobydob.github.io#4]
The Only Mod that is Working Correctly is the CG5 Mod Nothing else is loading not sure for everyone else though.

**Comment by bobydob** [comment]
what device do you have?
for me all mods work.

**Comment by FridayNightFunkinGame** [comment]
Windows 10 idk what is causing it.

**Comment by bobydob** [comment]
which mod?

**Comment by FridayNightFunkinGame** [comment]
🤷

**Comment by bobydob** [comment]
unfortunately I do not understand you. 
for me all mods work on PC Windows 10

**Comment by FridayNightFunkinGame** [comment]
Ok i guess its get my computer thank you
